name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 200

      - name: Lint Lua Code
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning
      
      - name: Lint Shell Scripts
        uses: ludeeus/action-shellcheck@master

      - name: Create Package
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}